import type { ThemeSettings } from "@/config/theme";

/**
 * Preset themes (Phase 9) - 10 curated palettes selectable from
 * /admin/theme-settings. Each preset maps onto the ThemeSettings shape;
 * applying one fills the color fields of the settings form and is then
 * persisted like any other theme change.
 */

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  theme: Partial<ThemeSettings>;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "cosmic-royal",
    name: "Cosmic Royal",
    description:
      "The signature look: deep royal purple, indigo and bright gold accents.",
    theme: {
      primary: "#4C1D95",
      secondary: "#312E81",
      accent: "#FACC15",
      accent2: "#D4AF37",
      accent3: "#F97316",
      whatsapp: "#25D366",
      emerald: "#16A34A",
      deepNavy: "#0F172A",
      pageBackground: "#0F172A",
      primaryTextColor: "#0F172A",
      secondaryTextColor: "#64748B",
      ctaPrimary: "#4C1D95",
      cardBackground: "#FFF7ED",
      cardBorder: "#D4AF37",
      heroGradientStart: "#0F172A",
      heroGradientEnd: "#4C1D95",
      topbarGradientStart: "#0F172A",
      topbarGradientEnd: "#4C1D95",
      footerGradientStart: "#111827",
      footerGradientEnd: "#312E81",
      goldGradientStart: "#FACC15",
      goldGradientEnd: "#F97316",
      legalTitleColor: "#4C1D95",
      legalBreadcrumbColor: "#111827",
      legalCardBackground: "#FFFFFF",
      legalCardBorder: "#D4AF37",
      legalTextColor: "#111827",
      legalHeadingColor: "#4C1D95",
      contactFormSurface: "#1E1B4B",
      contactFormLabelColor: "#FFFFFF",
      experienceBannerBackground: "#FACC15",
      experienceBannerTextColor: "#111827",
      experienceBannerBorder: "#D4AF37",
      topbarBackground: "#0F172A",
      topbarTextColor: "#D4AF37",
      announcementBar1Background: "#D4AF37",
      announcementBar1TextColor: "#0F172A",
      announcementBar2Background: "#0F172A",
      announcementBar2TextColor: "#FACC15",
      footerBackground: "#111827",
      footerHeadingColor: "#FACC15",
    },
  },
  {
    id: "golden-sunrise",
    name: "Golden Sunrise",
    description:
      "Warm maroon, deep indigo night and bright butter-yellow gold tones.",
    theme: {
      primary: "#800000",
      secondary: "#1E1B4B",
      accent: "#FDE047",
      accent2: "#D4AF37",
      accent3: "#D97706",
      whatsapp: "#25D366",
      emerald: "#16A34A",
      deepNavy: "#1E1B4B",
      pageBackground: "#1E1B4B",
      primaryTextColor: "#1E1B4B",
      secondaryTextColor: "#64748B",
      ctaPrimary: "#800000",
      cardBackground: "#FFFBEB",
      cardBorder: "#D4AF37",
      heroGradientStart: "#1E1B4B",
      heroGradientEnd: "#6E1535",
      topbarGradientStart: "#1E1B4B",
      topbarGradientEnd: "#6E1535",
      footerGradientStart: "#111827",
      footerGradientEnd: "#1E1B4B",
      goldGradientStart: "#FDE047",
      goldGradientEnd: "#D97706",
      legalTitleColor: "#800000",
      legalBreadcrumbColor: "#111827",
      legalCardBackground: "#FFFFFF",
      legalCardBorder: "#D4AF37",
      legalTextColor: "#111827",
      legalHeadingColor: "#800000",
      contactFormSurface: "#1E1B4B",
      contactFormLabelColor: "#FFFFFF",
      experienceBannerBackground: "#FDE047",
      experienceBannerTextColor: "#800000",
      experienceBannerBorder: "#D4AF37",
      topbarBackground: "#1E1B4B",
      topbarTextColor: "#FDE047",
      announcementBar1Background: "#FDE047",
      announcementBar1TextColor: "#111827",
      announcementBar2Background: "#800000",
      announcementBar2TextColor: "#FFFBEB",
      footerBackground: "#111827",
      footerHeadingColor: "#FDE047",
    },
  },
  {
    id: "vibrant-celestial",
    name: "Vibrant Celestial",
    description:
      "Bright electric violet, teal and amber - a modern cosmic energy.",
    theme: {
      primary: "#7C3AED",
      secondary: "#14B8A6",
      accent: "#F59E0B",
      accent2: "#FBBF24",
      accent3: "#EF4444",
      whatsapp: "#25D366",
      emerald: "#14B8A6",
      deepNavy: "#0F172A",
      pageBackground: "#0F172A",
      primaryTextColor: "#0F172A",
      secondaryTextColor: "#64748B",
      ctaPrimary: "#7C3AED",
      cardBackground: "#FFF7ED",
      cardBorder: "#FBBF24",
      heroGradientStart: "#0F172A",
      heroGradientEnd: "#7C3AED",
      topbarGradientStart: "#0F172A",
      topbarGradientEnd: "#14B8A6",
      footerGradientStart: "#111827",
      footerGradientEnd: "#14B8A6",
      goldGradientStart: "#F59E0B",
      goldGradientEnd: "#D97706",
      legalTitleColor: "#7C3AED",
      legalBreadcrumbColor: "#111827",
      legalCardBackground: "#FFFFFF",
      legalCardBorder: "#FBBF24",
      legalTextColor: "#111827",
      legalHeadingColor: "#7C3AED",
      contactFormSurface: "#111827",
      contactFormLabelColor: "#FFFFFF",
      experienceBannerBackground: "#F59E0B",
      experienceBannerTextColor: "#111827",
      experienceBannerBorder: "#FBBF24",
      topbarBackground: "#0F172A",
      topbarTextColor: "#14B8A6",
      announcementBar1Background: "#14B8A6",
      announcementBar1TextColor: "#0F172A",
      announcementBar2Background: "#7C3AED",
      announcementBar2TextColor: "#FFFFFF",
      footerBackground: "#111827",
      footerHeadingColor: "#14B8A6",
    },
  },
  {
    id: "deep-space-luxe",
    name: "Deep Space Luxe",
    description:
      "Premium high-contrast: rich purple, midnight navy, champagne gold and emerald.",
    theme: {
      primary: "#4C1D95",
      secondary: "#1E1B4B",
      accent: "#D4AF37",
      accent2: "#EAB308",
      accent3: "#B45309",
      whatsapp: "#10B981",
      emerald: "#10B981",
      deepNavy: "#0F172A",
      pageBackground: "#0F172A",
      primaryTextColor: "#0F172A",
      secondaryTextColor: "#64748B",
      ctaPrimary: "#4C1D95",
      cardBackground: "#FFF7ED",
      cardBorder: "#D4AF37",
      heroGradientStart: "#0F172A",
      heroGradientEnd: "#4C1D95",
      topbarGradientStart: "#0F172A",
      topbarGradientEnd: "#4C1D95",
      footerGradientStart: "#111827",
      footerGradientEnd: "#1E1B4B",
      goldGradientStart: "#D4AF37",
      goldGradientEnd: "#B45309",
      legalTitleColor: "#4C1D95",
      legalBreadcrumbColor: "#111827",
      legalCardBackground: "#FFFFFF",
      legalCardBorder: "#D4AF37",
      legalTextColor: "#111827",
      legalHeadingColor: "#4C1D95",
      contactFormSurface: "#1E1B4B",
      contactFormLabelColor: "#FFFFFF",
      experienceBannerBackground: "#D4AF37",
      experienceBannerTextColor: "#111827",
      experienceBannerBorder: "#B45309",
      topbarBackground: "#0F172A",
      topbarTextColor: "#D4AF37",
      announcementBar1Background: "#10B981",
      announcementBar1TextColor: "#FFFFFF",
      announcementBar2Background: "#D4AF37",
      announcementBar2TextColor: "#0F172A",
      footerBackground: "#111827",
      footerHeadingColor: "#D4AF37",
    },
  },
  {
    id: "royal-emerald",
    name: "Royal Emerald",
    description:
      "Deep forest green with a rich gold and bright emerald glow.",
    theme: {
      primary: "#10B981",
      secondary: "#065F46",
      accent: "#D4AF37",
      accent2: "#F5D04C",
      accent3: "#34D399",
      whatsapp: "#25D366",
      emerald: "#10B981",
      deepNavy: "#0F2C1D",
      pageBackground: "#0F2C1D",
      primaryTextColor: "#0F2C1D",
      secondaryTextColor: "#64748B",
      ctaPrimary: "#10B981",
      cardBackground: "#F0FDF4",
      cardBorder: "#D4AF37",
      heroGradientStart: "#0F2C1D",
      heroGradientEnd: "#065F46",
      topbarGradientStart: "#0F2C1D",
      topbarGradientEnd: "#065F46",
      footerGradientStart: "#0A1A11",
      footerGradientEnd: "#065F46",
      goldGradientStart: "#D4AF37",
      goldGradientEnd: "#34D399",
      legalTitleColor: "#0F766E",
      legalBreadcrumbColor: "#111827",
      legalCardBackground: "#FFFFFF",
      legalCardBorder: "#D4AF37",
      legalTextColor: "#111827",
      legalHeadingColor: "#065F46",
      contactFormSurface: "#0F2C1D",
      contactFormLabelColor: "#FFFFFF",
      experienceBannerBackground: "#10B981",
      experienceBannerTextColor: "#FFFFFF",
      experienceBannerBorder: "#D4AF37",
      topbarBackground: "#0F2C1D",
      topbarTextColor: "#D4AF37",
      announcementBar1Background: "#10B981",
      announcementBar1TextColor: "#FFFFFF",
      announcementBar2Background: "#D4AF37",
      announcementBar2TextColor: "#0F2C1D",
      footerBackground: "#0A1A11",
      footerHeadingColor: "#10B981",
    },
  },
  {
    id: "midnight-sapphire",
    name: "Midnight Sapphire",
    description:
      "Deep sapphire blue with a bright silver and royal blue glow.",
    theme: {
      primary: "#2563EB",
      secondary: "#1E3A8A",
      accent: "#E2E8F0",
      accent2: "#94A3B8",
      accent3: "#60A5FA",
      whatsapp: "#25D366",
      emerald: "#2563EB",
      deepNavy: "#0B132B",
      pageBackground: "#0B132B",
      primaryTextColor: "#0B132B",
      secondaryTextColor: "#64748B",
      ctaPrimary: "#2563EB",
      cardBackground: "#F8FAFC",
      cardBorder: "#94A3B8",
      heroGradientStart: "#0B132B",
      heroGradientEnd: "#1E3A8A",
      topbarGradientStart: "#0B132B",
      topbarGradientEnd: "#1E3A8A",
      footerGradientStart: "#070E1A",
      footerGradientEnd: "#1E3A8A",
      goldGradientStart: "#E2E8F0",
      goldGradientEnd: "#2563EB",
      legalTitleColor: "#2563EB",
      legalBreadcrumbColor: "#111827",
      legalCardBackground: "#FFFFFF",
      legalCardBorder: "#94A3B8",
      legalTextColor: "#111827",
      legalHeadingColor: "#2563EB",
      contactFormSurface: "#0B132B",
      contactFormLabelColor: "#E2E8F0",
      experienceBannerBackground: "#E2E8F0",
      experienceBannerTextColor: "#0B132B",
      experienceBannerBorder: "#2563EB",
      topbarBackground: "#0B132B",
      topbarTextColor: "#E2E8F0",
      announcementBar1Background: "#1E3A8A",
      announcementBar1TextColor: "#E2E8F0",
      announcementBar2Background: "#E2E8F0",
      announcementBar2TextColor: "#0B132B",
      footerBackground: "#070E1A",
      footerHeadingColor: "#2563EB",
    },
  },
  {
    id: "velvet-rose",
    name: "Velvet Rose",
    description:
      "Deep maroon velvet with soft cream and muted gold accents.",
    theme: {
      primary: "#800000",
      secondary: "#5C0E1F",
      accent: "#FFF7ED",
      accent2: "#B8860B",
      accent3: "#E3B04B",
      whatsapp: "#25D366",
      emerald: "#16A34A",
      deepNavy: "#2D0A13",
      pageBackground: "#2D0A13",
      primaryTextColor: "#2D0A13",
      secondaryTextColor: "#94A3B8",
      ctaPrimary: "#800000",
      cardBackground: "#FFF7ED",
      cardBorder: "#B8860B",
      heroGradientStart: "#2D0A13",
      heroGradientEnd: "#800000",
      topbarGradientStart: "#2D0A13",
      topbarGradientEnd: "#800000",
      footerGradientStart: "#1A050A",
      footerGradientEnd: "#5C0E1F",
      goldGradientStart: "#E3B04B",
      goldGradientEnd: "#FFF7ED",
      legalTitleColor: "#800000",
      legalBreadcrumbColor: "#111827",
      legalCardBackground: "#FFFFFF",
      legalCardBorder: "#B8860B",
      legalTextColor: "#111827",
      legalHeadingColor: "#800000",
      contactFormSurface: "#2D0A13",
      contactFormLabelColor: "#FFF7ED",
      experienceBannerBackground: "#B8860B",
      experienceBannerTextColor: "#FFF7ED",
      experienceBannerBorder: "#E3B04B",
      topbarBackground: "#2D0A13",
      topbarTextColor: "#FFF7ED",
      announcementBar1Background: "#800000",
      announcementBar1TextColor: "#FFF7ED",
      announcementBar2Background: "#FFF7ED",
      announcementBar2TextColor: "#2D0A13",
      footerBackground: "#1A050A",
      footerHeadingColor: "#B8860B",
    },
  },
  {
    id: "ash-charcoal",
    name: "Ash & Charcoal",
    description:
      "Modern minimalist dark: warm charcoal with ash grey and warm white.",
    theme: {
      primary: "#374151",
      secondary: "#4B5563",
      accent: "#9CA3AF",
      accent2: "#CBD5E1",
      accent3: "#6B7280",
      whatsapp: "#25D366",
      emerald: "#16A34A",
      deepNavy: "#1A1A1A",
      pageBackground: "#1A1A1A",
      primaryTextColor: "#1A1A1A",
      secondaryTextColor: "#9CA3AF",
      ctaPrimary: "#374151",
      cardBackground: "#F3F4F6",
      cardBorder: "#9CA3AF",
      heroGradientStart: "#1A1A1A",
      heroGradientEnd: "#374151",
      topbarGradientStart: "#1A1A1A",
      topbarGradientEnd: "#374151",
      footerGradientStart: "#0F0F0F",
      footerGradientEnd: "#1A1A1A",
      goldGradientStart: "#D1D5DB",
      goldGradientEnd: "#6B7280",
      legalTitleColor: "#374151",
      legalBreadcrumbColor: "#111827",
      legalCardBackground: "#FFFFFF",
      legalCardBorder: "#9CA3AF",
      legalTextColor: "#111827",
      legalHeadingColor: "#374151",
      contactFormSurface: "#1A1A1A",
      contactFormLabelColor: "#F3F4F6",
      experienceBannerBackground: "#9CA3AF",
      experienceBannerTextColor: "#1A1A1A",
      experienceBannerBorder: "#6B7280",
      topbarBackground: "#1A1A1A",
      topbarTextColor: "#9CA3AF",
      announcementBar1Background: "#374151",
      announcementBar1TextColor: "#F3F4F6",
      announcementBar2Background: "#F3F4F6",
      announcementBar2TextColor: "#1A1A1A",
      footerBackground: "#0F0F0F",
      footerHeadingColor: "#F3F4F6",
    },
  },
  {
    id: "butter-gold",
    name: "Butter Gold",
    description:
      "Soft warm butter with dark gold accents and deep brown - a light, luxurious theme.",
    theme: {
      primary: "#3D2B1F",
      secondary: "#8B5E34",
      accent: "#B8860B",
      accent2: "#C9A227",
      accent3: "#A16207",
      whatsapp: "#25D366",
      emerald: "#16A34A",
      deepNavy: "#3D2B1F",
      pageBackground: "#FFF3D4",
      primaryTextColor: "#3D2B1F",
      secondaryTextColor: "#7A5C40",
      ctaPrimary: "#B8860B",
      cardBackground: "#FFFFFF",
      cardBorder: "#C9A227",
      heroGradientStart: "#4C2E1A",
      heroGradientEnd: "#241708",
      topbarGradientStart: "#4C2E1A",
      topbarGradientEnd: "#241708",
      footerGradientStart: "#2A1D14",
      footerGradientEnd: "#1E140D",
      goldGradientStart: "#FFD966",
      goldGradientEnd: "#B8860B",
      legalTitleColor: "#3D2B1F",
      legalBreadcrumbColor: "#57534E",
      legalCardBackground: "#FFFFFF",
      legalCardBorder: "#C9A227",
      legalTextColor: "#3D2B1F",
      legalHeadingColor: "#3D2B1F",
      contactFormSurface: "#3D2B1F",
      contactFormLabelColor: "#FFF3D4",
      experienceBannerBackground: "#D4AF37",
      experienceBannerTextColor: "#3D2B1F",
      experienceBannerBorder: "#B8860B",
      topbarBackground: "#3D2B1F",
      topbarTextColor: "#FFF3D4",
      announcementBar1Background: "#D4AF37",
      announcementBar1TextColor: "#3D2B1F",
      announcementBar2Background: "#3D2B1F",
      announcementBar2TextColor: "#FFF3D4",
      footerBackground: "#2A1D14",
      footerHeadingColor: "#D4AF37",
    },
  },
  {
    id: "mystic-violet",
    name: "Mystic Violet",
    description:
      "Deep violet night with lavender and bright purple accents.",
    theme: {
      primary: "#7C3AED",
      secondary: "#4C1D95",
      accent: "#D8B4FE",
      accent2: "#A78BFA",
      accent3: "#6D28D9",
      whatsapp: "#25D366",
      emerald: "#16A34A",
      deepNavy: "#1A0B2E",
      pageBackground: "#1A0B2E",
      primaryTextColor: "#1A0B2E",
      secondaryTextColor: "#A5B4FC",
      ctaPrimary: "#7C3AED",
      cardBackground: "#FAF5FF",
      cardBorder: "#A78BFA",
      heroGradientStart: "#1A0B2E",
      heroGradientEnd: "#4C1D95",
      topbarGradientStart: "#1A0B2E",
      topbarGradientEnd: "#4C1D95",
      footerGradientStart: "#0F0518",
      footerGradientEnd: "#4C1D95",
      goldGradientStart: "#D8B4FE",
      goldGradientEnd: "#7C3AED",
      legalTitleColor: "#6D28D9",
      legalBreadcrumbColor: "#111827",
      legalCardBackground: "#FFFFFF",
      legalCardBorder: "#A78BFA",
      legalTextColor: "#111827",
      legalHeadingColor: "#6D28D9",
      contactFormSurface: "#1A0B2E",
      contactFormLabelColor: "#D8B4FE",
      experienceBannerBackground: "#D8B4FE",
      experienceBannerTextColor: "#1A0B2E",
      experienceBannerBorder: "#7C3AED",
      topbarBackground: "#1A0B2E",
      topbarTextColor: "#D8B4FE",
      announcementBar1Background: "#4C1D95",
      announcementBar1TextColor: "#D8B4FE",
      announcementBar2Background: "#D8B4FE",
      announcementBar2TextColor: "#1A0B2E",
      footerBackground: "#0F0518",
      footerHeadingColor: "#7C3AED",
    },
  },
];

export function themePresetById(id: string | null | undefined): ThemePreset | undefined {
  return THEME_PRESETS.find((p) => p.id === id);
}
