export interface Family {
  category: "spiritual" | "vastu";
  group: string;
  groupSlug: string;
  typeName: string;
  typeSlug: string;
  productBase: string;
  slugBase: string;
  intro: string;
  whatYouReceive: string;
  howToUse: string;
  material: string;
  color: string;
  weight: string;
  prices: [number, number, number];
  sizeMode: "yantra" | "standard" | "units";
  sizeLabels: [string, string, string];
  tags: string[];
  benefits: string[];
  sizeChildren?: boolean;
}

export const FAMILIES: Family[] = [
  // ---------------- Spiritual Items ----------------
  {
    category: "spiritual",
    group: "Yantras",
    groupSlug: "cat-spiritual-items-group-yantras",
    typeName: "Meru Prasth (Shree Yantra)",
    typeSlug: "cat-spiritual-items-group-yantras-type-meru-prasth",
    productBase: "Shree Yantra (Meru Prasth)",
    slugBase: "shree-yantra-meru-prasth",
    intro:
      "The Shree Yantra in Meru Prasth form — the three-dimensional summit of the Sri Yantra, revered as the abode of Maa Lakshmi and the most powerful yantra for prosperity, harmony and spiritual growth.",
    whatYouReceive: "Copper. Meru (3D) Prasth form. Approx. 5x5 cm base.",
    howToUse: "Place in the northeast (Ishaan) corner of the home or puja room; worship on Fridays and during Diwali.",
    material: "Copper",
    color: "Copper",
    weight: "Approx. 55 g",
    prices: [599, 1199, 2199],
    sizeMode: "yantra",
    sizeLabels: ["3-inch", "6-inch", "9-inch"],
    tags: ["shree yantra", "meru prasth", "sri yantra", "prosperity", "lakshmi"],
    benefits: [
      "Three-dimensional Meru form of the Sri Yantra",
      "Revered as the abode of Maa Lakshmi",
      "Classic copper engraving with fine detailing",
      "Placed in the northeast for harmony and growth",
    ],
    sizeChildren: true,
  },
  {
    category: "spiritual",
    group: "Natural & Ritual Elements",
    groupSlug: "cat-spiritual-items-group-natural-ritual-elements",
    typeName: "Gomati Chakras & Laxmi Kaudi Shells",
    typeSlug: "cat-spiritual-items-group-natural-ritual-elements-type-gomati-chakras-laxmi-kaudi",
    productBase: "Gomati Chakras & Laxmi Kaudi Shells",
    slugBase: "gomati-chakras-laxmi-kaudi-shells",
    intro:
      "Sacred Gomati chakras and Laxmi kaudi shells — natural white and yellow shells considered the goddess Lakshmi's gift, traditionally kept in cash boxes, lockers and puja rooms to attract wealth and good fortune.",
    whatYouReceive: "Natural Gomati chakras with Laxmi kaudi shells. Set in a cotton pouch.",
    howToUse: "Keep in the cash box, locker or puja room; offer during Laxmi Puja and Diwali.",
    material: "Natural Shells",
    color: "White / Yellow",
    weight: "Approx. 50 g",
    prices: [299, 599, 1099],
    sizeMode: "standard",
    sizeLabels: ["Small", "Medium", "Large"],
    tags: ["gomati chakra", "laxmi kaudi", "cowrie", "wealth", "prosperity"],
    benefits: [
      "Natural Gomati chakras and kaudi shells",
      "Considered a blessing of Maa Lakshmi",
      "Traditionally kept with cash and valuables",
      "Adds positive energy to the puja room",
    ],
  },
  {
    category: "spiritual",
    group: "Altar Essentials",
    groupSlug: "cat-spiritual-items-group-altar-essentials",
    typeName: "Crystal Lotus & Orgonite Pyramids",
    typeSlug: "cat-spiritual-items-group-altar-essentials-type-crystal-lotus-orgonite-pyramids",
    productBase: "Crystal Lotus & Orgonite Pyramids",
    slugBase: "crystal-lotus-orgonite-pyramids",
    intro:
      "A handcrafted crystal lotus and orgonite pyramid set — combining the purity of crystal with orgonite's reputed energy-clearing properties, ideal for desks, meditation corners and puja altars.",
    whatYouReceive: "Crystal lotus with orgonite pyramid. Handcrafted with resin and crystal chips.",
    howToUse: "Place on the desk, meditation corner or altar; cleanse weekly under running water or moonlight.",
    material: "Crystal & Resin",
    color: "Clear / Rainbow",
    weight: "Approx. 120 g",
    prices: [899, 1799, 3399],
    sizeMode: "standard",
    sizeLabels: ["Small", "Medium", "Large"],
    tags: ["crystal lotus", "orgonite pyramid", "energy", "meditation"],
    benefits: [
      "Crystal lotus with orgonite pyramid",
      "Reputed to clear and balance surrounding energy",
      "Handcrafted for altar and desk decor",
      "Great companion for meditation practice",
    ],
  },
  {
    category: "spiritual",
    group: "Altar Essentials",
    groupSlug: "cat-spiritual-items-group-altar-essentials",
    typeName: "Panchdhatu Bells (Puja Ghanti)",
    typeSlug: "cat-spiritual-items-group-altar-essentials-type-panchdhatu-bells-puja-ghanti",
    productBase: "Panchdhatu Bell (Puja Ghanti)",
    slugBase: "panchdhatu-bell-puja-ghanti",
    intro:
      "A traditional Panchdhatu puja ghanti — a five-metal bell with a carved wooden handle, rung during aarti and puja to invoke divine presence and cleanse the atmosphere.",
    whatYouReceive: "Panchdhatu bell with wooden handle. Five-metal alloy (gold, silver, copper, zinc, iron).",
    howToUse: "Ring during aarti, puja and mantra chanting; keep on the altar when not in use.",
    material: "Panchdhatu (5 Metals)",
    color: "Golden",
    weight: "Approx. 250 g",
    prices: [499, 999, 1899],
    sizeMode: "standard",
    sizeLabels: ["2-inch", "3-inch", "4-inch"],
    tags: ["puja ghanti", "panchdhatu bell", "aarti", "temple bell"],
    benefits: [
      "Authentic Panchdhatu (five-metal) composition",
      "Deep resonant sound for aarti and puja",
      "Carved wooden handle for a firm grip",
      "Traditional temple-style craftsmanship",
    ],
  },
  {
    category: "spiritual",
    group: "Altar Essentials",
    groupSlug: "cat-spiritual-items-group-altar-essentials",
    typeName: "Brass Altar Frames (Prabhavali)",
    typeSlug: "cat-spiritual-items-group-altar-essentials-type-brass-altar-frames-prabhavali",
    productBase: "Brass Altar Frame (Prabhavali)",
    slugBase: "brass-altar-frame-prabhavali",
    intro:
      "A polished brass prabhavali — the traditional ornate arch frame that cradles deity murtis on the home altar, lending a temple-like grandeur to your puja space.",
    whatYouReceive: "Polished brass prabhavali frame. Ornate arched design with intricate detailing.",
    howToUse: "Place behind the deity murti on the altar; polish occasionally with a soft cloth.",
    material: "Brass",
    color: "Golden",
    weight: "Approx. 400 g",
    prices: [999, 1999, 3799],
    sizeMode: "standard",
    sizeLabels: ["6-inch", "9-inch", "12-inch"],
    tags: ["prabhavali", "brass altar frame", "deity frame", "puja"],
    benefits: [
      "Traditional ornate prabhavali arch design",
      "Polished brass with intricate detailing",
      "Elevates the home altar to temple-like grandeur",
      "Sturdy frame holds murtis securely",
    ],
  },
  {
    category: "spiritual",
    group: "Altar Essentials",
    groupSlug: "cat-spiritual-items-group-altar-essentials",
    typeName: "Singhasans (Deity Thrones)",
    typeSlug: "cat-spiritual-items-group-altar-essentials-type-singhasans-deity-thrones",
    productBase: "Singhasan (Deity Throne)",
    slugBase: "singhasan-deity-throne",
    intro:
      "A carved singhasan — the traditional throne or seat for deity murtis on the home altar, handcrafted in wood with a regal finish befitting your puja room.",
    whatYouReceive: "Handcrafted wooden singhasan. Carved with traditional motifs.",
    howToUse: "Place the deity murti on the singhasan at the altar; dust regularly with a dry cloth.",
    material: "Wood",
    color: "Golden",
    weight: "Approx. 800 g",
    prices: [1999, 3999, 7499],
    sizeMode: "standard",
    sizeLabels: ["Small", "Medium", "Large"],
    tags: ["singhasan", "deity throne", "murti seat", "altar"],
    benefits: [
      "Traditional hand-carved singhasan throne",
      "Dignified seat for deity murtis",
      "Regal golden finish for the altar",
      "Sturdy build for daily puja use",
    ],
  },
  {
    category: "spiritual",
    group: "Altar Essentials",
    groupSlug: "cat-spiritual-items-group-altar-essentials",
    typeName: "Poshaks & Chunris",
    typeSlug: "cat-spiritual-items-group-altar-essentials-type-poshaks-chunris",
    productBase: "Poshaks & Chunris",
    slugBase: "poshaks-chunris",
    intro:
      "Traditional poshaks and chunris — finely stitched silk and cotton garments for dressing deity murtis, available in vibrant festive colours to adorn your altar with devotion.",
    whatYouReceive: "Poshak set with chunri. Fine silk/cotton fabric in festive colours.",
    howToUse: "Dress the deity murti during festivals, weddings and special pujas.",
    material: "Silk & Cotton",
    color: "Multi-colour",
    weight: "Approx. 100 g",
    prices: [599, 1199, 2299],
    sizeMode: "standard",
    sizeLabels: ["Small", "Medium", "Large"],
    tags: ["poshak", "chunri", "deity dress", "murti garments"],
    benefits: [
      "Traditional poshak and chunri set",
      "Fine silk and cotton fabrics",
      "Vibrant festive colours",
      "Fits standard murti sizes",
    ],
  },
  {
    category: "spiritual",
    group: "Sacred Idols",
    groupSlug: "cat-spiritual-items-group-sacred-idols",
    typeName: "Panchdhatu Idols",
    typeSlug: "cat-spiritual-items-group-sacred-idols-type-panchdhatu-idols",
    productBase: "Panchdhatu Idols",
    slugBase: "panchdhatu-idols",
    intro:
      "Panchdhatu murtis — idols of beloved deities cast in the sacred five-metal alloy, hand-finished with fine detailing to grace your home altar or office.",
    whatYouReceive: "Panchdhatu idol. Five-metal alloy cast with fine detailing.",
    howToUse: "Place on the altar or desk; perform daily puja with the idol as the focal point.",
    material: "Panchdhatu (5 Metals)",
    color: "Golden",
    weight: "Approx. 300 g",
    prices: [1299, 2599, 4999],
    sizeMode: "standard",
    sizeLabels: ["3-inch", "5-inch", "7-inch"],
    tags: ["panchdhatu idol", "murti", "deity idol", "puja"],
    benefits: [
      "Sacred Panchdhatu (five-metal) alloy",
      "Hand-finished fine detailing",
      "Suitable for home altar and office",
      "Durable cast for daily puja",
    ],
  },
  {
    category: "spiritual",
    group: "Sound & Vibration Tools",
    groupSlug: "cat-spiritual-items-group-sound-vibration-tools",
    typeName: "Tingsha Cymbals",
    typeSlug: "cat-spiritual-items-group-sound-vibration-tools-type-tingsha-cymbals",
    productBase: "Tingsha Cymbals",
    slugBase: "tingsha-cymbals",
    intro:
      "Traditional tingsha cymbals — small hand-forged Tibetan cymbals joined by a leather strap, struck together to produce a clear, purifying ring used in meditation and sound healing.",
    whatYouReceive: "Pair of hand-forged tingsha cymbals with leather strap.",
    howToUse: "Strike the cymbals gently together before and after meditation to open and close the practice.",
    material: "Metal Alloy (Tibetan)",
    color: "Golden",
    weight: "Approx. 60 g",
    prices: [799, 1599, 2999],
    sizeMode: "standard",
    sizeLabels: ["2-inch", "3-inch", "4-inch"],
    tags: ["tingsha", "cymbals", "tibetan", "meditation", "sound healing"],
    benefits: [
      "Hand-forged traditional Tibetan tingsha",
      "Clear purifying ring for meditation",
      "Portable with leather strap",
      "Used in sound healing practice",
    ],
  },
  {
    category: "spiritual",
    group: "Puja & Ritual Items",
    groupSlug: "cat-spiritual-items-group-puja-ritual-items",
    typeName: "Shankh (Conch Shells)",
    typeSlug: "cat-spiritual-items-group-puja-ritual-items-type-shankh-conch-shells",
    productBase: "Shankh (Conch Shell)",
    slugBase: "shankh-conch-shell",
    intro:
      "A natural shankh — an authentic conch shell blown during puja and aarti, believed to purify the atmosphere with its sacred sound and bring good fortune.",
    whatYouReceive: "Natural conch shell (shankh). Cleaned and polished.",
    howToUse: "Blow during aarti and puja, or display on the altar; clean with a damp cloth.",
    material: "Natural Conch Shell",
    color: "White / Cream",
    weight: "Approx. 200 g",
    prices: [699, 1399, 2599],
    sizeMode: "standard",
    sizeLabels: ["Small", "Medium", "Large"],
    tags: ["shankh", "conch shell", "puja", "aarti"],
    benefits: [
      "Authentic natural conch shell",
      "Sacred sound purifies the atmosphere",
      "Traditionally blown during aarti",
      "Also a beautiful altar display piece",
    ],
  },
  {
    category: "spiritual",
    group: "Puja & Ritual Items",
    groupSlug: "cat-spiritual-items-group-puja-ritual-items",
    typeName: "Camphor Tablets (Bhimseni Kapoor)",
    typeSlug: "cat-spiritual-items-group-puja-ritual-items-type-camphor-tablets-bhimseni-kapoor",
    productBase: "Camphor Tablets (Bhimseni Kapoor)",
    slugBase: "camphor-tablets-bhimseni-kapoor",
    intro:
      "Pure Bhimseni camphor tablets — natural camphor used in aarti, havan and healing rituals, known for its pure white flame and calming fragrance.",
    whatYouReceive: "Natural Bhimseni camphor tablets. Food-grade purity.",
    howToUse: "Light a tablet during aarti or havan; keep in an airtight container when not in use.",
    material: "Natural Camphor",
    color: "White",
    weight: "Approx. 50 g",
    prices: [149, 299, 549],
    sizeMode: "units",
    sizeLabels: ["25 g", "50 g", "100 g"],
    tags: ["camphor", "bhimseni kapoor", "aarti", "havan"],
    benefits: [
      "Pure natural Bhimseni camphor",
      "Bright white flame for aarti",
      "Calming traditional fragrance",
      "Suitable for havan and rituals",
    ],
  },
  {
    category: "spiritual",
    group: "Puja & Ritual Items",
    groupSlug: "cat-spiritual-items-group-puja-ritual-items",
    typeName: "Dhoop Sticks",
    typeSlug: "cat-spiritual-items-group-puja-ritual-items-type-dhoop-sticks",
    productBase: "Dhoop Sticks",
    slugBase: "dhoop-sticks",
    intro:
      "Natural dhoop sticks — slow-burning incense sticks hand-rolled with natural herbs and resins, filling the home with a soothing aroma during puja and meditation.",
    whatYouReceive: "Hand-rolled natural dhoop sticks. Herbal and resin blend.",
    howToUse: "Light the tip, let the flame settle, and place in a dhoop stand during puja or meditation.",
    material: "Natural Herbs & Resin",
    color: "Brown",
    weight: "Approx. 40 g",
    prices: [149, 299, 549],
    sizeMode: "units",
    sizeLabels: ["10 sticks", "25 sticks", "50 sticks"],
    tags: ["dhoop", "incense sticks", "puja", "meditation"],
    benefits: [
      "Hand-rolled natural herbal blend",
      "Slow-burning long-lasting aroma",
      "Traditional puja and meditation incense",
      "Soothing and calming fragrance",
    ],
  },
  {
    category: "spiritual",
    group: "Incense & Resins",
    groupSlug: "cat-spiritual-items-group-incense-resins",
    typeName: "Sambrani Cups",
    typeSlug: "cat-spiritual-items-group-incense-resins-type-sambrani-cups",
    productBase: "Sambrani Cups",
    slugBase: "sambrani-cups",
    intro:
      "Traditional sambrani cups — resinous benzoin incense cups that release a rich, purifying smoke when lit, used in home rituals and for cleansing the atmosphere.",
    whatYouReceive: "Traditional sambrani cups. Resinous benzoin blend.",
    howToUse: "Light the cup in a heat-proof holder and let the fragrant smoke purify the space.",
    material: "Benzoin Resin",
    color: "Dark Brown",
    weight: "Approx. 60 g",
    prices: [199, 399, 749],
    sizeMode: "units",
    sizeLabels: ["10 cups", "25 cups", "50 cups"],
    tags: ["sambrani", "benzoin", "incense", "purifying smoke"],
    benefits: [
      "Traditional resinous sambrani cups",
      "Rich purifying smoke",
      "Classic South Indian home ritual",
      "Long-lasting fragrant burn",
    ],
  },
  {
    category: "spiritual",
    group: "Incense & Resins",
    groupSlug: "cat-spiritual-items-group-incense-resins",
    typeName: "Attar (Natural Perfume Oil)",
    typeSlug: "cat-spiritual-items-group-incense-resins-type-attar-natural-perfume-oil",
    productBase: "Attar (Natural Perfume Oil)",
    slugBase: "attar-natural-perfume-oil",
    intro:
      "Natural attar — traditional perfume oils distilled from flowers and herbs without alcohol, offering a pure, long-lasting fragrance for personal use and puja offerings.",
    whatYouReceive: "Natural attar in a glass roll-on vial. Alcohol-free.",
    howToUse: "Apply a drop to the wrist or behind the ears; a few drops may also be offered in puja.",
    material: "Natural Essential Oils",
    color: "Golden",
    weight: "Approx. 10 ml",
    prices: [599, 1199, 2299],
    sizeMode: "units",
    sizeLabels: ["10 ml", "25 ml", "50 ml"],
    tags: ["attar", "perfume oil", "natural fragrance", "ittar"],
    benefits: [
      "Traditional alcohol-free natural attar",
      "Distilled from pure flowers and herbs",
      "Long-lasting and skin-friendly",
      "Suitable for personal and puja use",
    ],
  },
  // ---------------- Vastu Items ----------------
  {
    category: "vastu",
    group: "Yantras & Remedies",
    groupSlug: "cat-vastu-items-group-yantras-remedies",
    typeName: "Vastu Dosh Nivaran Yantra",
    typeSlug: "cat-vastu-items-group-yantras-remedies-type-vastu-dosh-nivaran-yantra",
    productBase: "Vastu Dosh Nivaran Yantra",
    slugBase: "vastu-dosh-nivaran-yantra",
    intro:
      "The Vastu Dosh Nivaran Yantra on copper — the classic remedy for balancing vastu defects of the home or office, traditionally installed to neutralise negative energies.",
    whatYouReceive: "Copper. Approx. 5x5 cm plate. Engraved with the vastu remedy mantra.",
    howToUse: "Install in the centre of the home or office, or near the main entrance; energise on Sundays.",
    material: "Copper",
    color: "Copper",
    weight: "Approx. 40 g",
    prices: [599, 1199, 2299],
    sizeMode: "yantra",
    sizeLabels: ["3-inch", "6-inch", "9-inch"],
    tags: ["vastu", "vastu dosh nivaran", "yantra", "remedies"],
    benefits: [
      "Classic vastu dosh nivaran remedy",
      "Balances the five elements of the space",
      "Copper plate with engraved mantra",
      "Compact size for home or office",
    ],
    sizeChildren: true,
  },
  {
    category: "vastu",
    group: "Zone Corrections",
    groupSlug: "cat-vastu-items-group-zone-corrections",
    typeName: "Vastu Helixes (Copper Zinc Lead)",
    typeSlug: "cat-vastu-items-group-zone-corrections-type-vastu-helixes-copper-zinc-lead",
    productBase: "Vastu Helixes (Copper Zinc Lead)",
    slugBase: "vastu-helixes-copper-zinc-lead",
    intro:
      "Copper, zinc and lead helixes — the classic vastu zone-correction tool, placed at the centre of a room to harmonise its energy field and correct zone imbalances.",
    whatYouReceive: "Set of copper, zinc and lead helixes. Pre-assembled in a small base.",
    howToUse: "Place the helix set at the centre of the room to be corrected; keep it undisturbed.",
    material: "Copper, Zinc & Lead",
    color: "Multi-metal",
    weight: "Approx. 150 g",
    prices: [899, 1799, 3299],
    sizeMode: "standard",
    sizeLabels: ["3-inch", "5-inch", "7-inch"],
    tags: ["vastu helix", "zone correction", "copper zinc lead", "vastu"],
    benefits: [
      "Classic three-metal vastu helix set",
      "Corrects zone imbalances of a room",
      "Pre-assembled for immediate use",
      "Small footprint for any room",
    ],
  },
  {
    category: "vastu",
    group: "Zone Corrections",
    groupSlug: "cat-vastu-items-group-zone-corrections",
    typeName: "Geopathic Stress Neutralizer Rods",
    typeSlug: "cat-vastu-items-group-zone-corrections-type-geopathic-stress-neutralizer-rods",
    productBase: "Geopathic Stress Neutralizer Rods",
    slugBase: "geopathic-stress-neutralizer-rods",
    intro:
      "Geopathic stress neutralizer rods — professional-grade copper rods tuned to neutralise harmful earth radiation (geopathic stress) under sleeping and working areas.",
    whatYouReceive: "Set of tuned copper neutralizer rods with placement guide.",
    howToUse: "Place the rods under the bed or workspace as per the guide to neutralise geopathic stress.",
    material: "Copper",
    color: "Copper",
    weight: "Approx. 500 g",
    prices: [1999, 3999, 7499],
    sizeMode: "standard",
    sizeLabels: ["3-inch", "5-inch", "7-inch"],
    tags: ["geopathic stress", "neutralizer", "copper rods", "vastu"],
    benefits: [
      "Tuned to neutralise geopathic stress",
      "Professional-grade copper construction",
      "For beds and workspaces",
      "Comes with placement guide",
    ],
  },
  {
    category: "vastu",
    group: "Showpieces & Statues",
    groupSlug: "cat-vastu-items-group-showpieces-statues",
    typeName: "Seven Running Horses",
    typeSlug: "cat-vastu-items-group-showpieces-statues-type-seven-running-horses",
    productBase: "Seven Running Horses",
    slugBase: "seven-running-horses",
    intro:
      "The Seven Running Horses — a symbol of speed, success and unstoppable momentum, available as a wall painting or tabletop idol to energise the living room or office.",
    whatYouReceive: "Seven running horses in a galloping composition. Painting or brass idol.",
    howToUse: "Place in the living room, hall or office facing inwards (towards the room).",
    material: "Canvas / Brass",
    color: "Multi-colour",
    weight: "Approx. 900 g",
    prices: [1299, 2599, 4999],
    sizeMode: "standard",
    sizeLabels: ["Small", "Medium", "Large"],
    tags: ["seven horses", "running horses", "success", "vastu decor"],
    benefits: [
      "Iconic symbol of speed and success",
      "Available as painting or idol",
      "Energises the living room or office",
      "Momentum and growth symbolism",
    ],
  },
  {
    category: "vastu",
    group: "Showpieces & Statues",
    groupSlug: "cat-vastu-items-group-showpieces-statues",
    typeName: "Kamdhenu Cow & Calf",
    typeSlug: "cat-vastu-items-group-showpieces-statues-type-kamdhenu-cow-calf",
    productBase: "Kamdhenu Cow & Calf",
    slugBase: "kamdhenu-cow-calf",
    intro:
      "The Kamdhenu cow with calf — the divine wish-fulfilling cow of the Puranas, crafted in brass as a symbol of abundance, nourishment and prosperity for the home altar.",
    whatYouReceive: "Brass Kamdhenu cow with calf. Hand-finished detailing.",
    howToUse: "Place in the puja room or the northeast corner of the home; worship during festivals.",
    material: "Brass",
    color: "Golden",
    weight: "Approx. 450 g",
    prices: [1499, 2999, 5499],
    sizeMode: "standard",
    sizeLabels: ["Small", "Medium", "Large"],
    tags: ["kamdhenu", "cow and calf", "abundance", "brass idol"],
    benefits: [
      "Divine Kamdhenu — the wish-fulfilling cow",
      "Brass craft with calf by her side",
      "Symbol of abundance and nourishment",
      "Beautiful altar centrepiece",
    ],
  },
  {
    category: "vastu",
    group: "Showpieces & Statues",
    groupSlug: "cat-vastu-items-group-showpieces-statues",
    typeName: "Gajraj (Elephants) Pair",
    typeSlug: "cat-vastu-items-group-showpieces-statues-type-gajraj-elephants-pair",
    productBase: "Gajraj (Elephants) Pair",
    slugBase: "gajraj-elephants-pair",
    intro:
      "A pair of Gajraj elephants — majestic brass elephants symbolising strength, wisdom and stability, traditionally placed at entrances for auspiciousness.",
    whatYouReceive: "Pair of brass Gajraj elephants. Hand-finished.",
    howToUse: "Place the pair at the entrance, hall or office shelf facing inwards.",
    material: "Brass",
    color: "Golden",
    weight: "Approx. 1.2 kg",
    prices: [1699, 3399, 6499],
    sizeMode: "standard",
    sizeLabels: ["6-inch", "9-inch", "12-inch"],
    tags: ["gajraj", "elephants pair", "brass elephants", "entrance decor"],
    benefits: [
      "Pair of majestic Gajraj elephants",
      "Symbols of strength and stability",
      "Traditional entrance auspiciousness",
      "Hand-finished brass craft",
    ],
  },
  {
    category: "vastu",
    group: "Protection & Amulets",
    groupSlug: "cat-vastu-items-group-protection-amulets",
    typeName: "Evil Eye Hangings",
    typeSlug: "cat-vastu-items-group-protection-amulets-type-evil-eye-hangings",
    productBase: "Evil Eye Hangings",
    slugBase: "evil-eye-hangings",
    intro:
      "Evil eye hangings — traditional protective amulets that deflect the nazar (evil eye), crafted in glass, brass or thread and hung at doors, vehicles or cradles.",
    whatYouReceive: "Evil eye hanging. Glass/brass with red thread.",
    howToUse: "Hang at the main door, in the vehicle, or near the cradle to ward off the nazar.",
    material: "Glass / Brass",
    color: "Blue / Red",
    weight: "Approx. 80 g",
    prices: [499, 999, 1899],
    sizeMode: "standard",
    sizeLabels: ["Small", "Medium", "Large"],
    tags: ["evil eye", "nazar", "protection", "amulet"],
    benefits: [
      "Traditional nazar protection amulet",
      "Hang at door, vehicle or cradle",
      "Crafted in glass and brass",
      "Classic blue-and-red evil eye",
    ],
  },
  {
    category: "vastu",
    group: "Decor & Flow Elements",
    groupSlug: "cat-vastu-items-group-decor-flow-elements",
    typeName: "Water Fountains & Urli Bowls",
    typeSlug: "cat-vastu-items-group-decor-flow-elements-type-water-fountains-urli-bowls",
    productBase: "Water Fountains & Urli Bowls",
    slugBase: "water-fountains-urli-bowls",
    intro:
      "Water fountains and urli bowls — the classic vastu and feng shui element of water, believed to attract wealth and positive energy; available as flowing fountains or traditional brass urli.",
    whatYouReceive: "Water fountain or brass urli bowl. Complete with recirculating pump (fountain) or stand (urli).",
    howToUse: "Place in the northeast corner or living area; keep the water clean and flowing.",
    material: "Brass / Resin",
    color: "Golden / Copper",
    weight: "Approx. 2 kg",
    prices: [1499, 2999, 5499],
    sizeMode: "standard",
    sizeLabels: ["Small", "Medium", "Large"],
    tags: ["water fountain", "urli bowl", "feng shui", "water element"],
    benefits: [
      "Classic water element for wealth and energy",
      "Flowing fountain or traditional brass urli",
      "Northeast corner placement",
      "Easy-maintenance design",
    ],
  },
];