"use client";

import Link from "next/link";
import { useState } from "react";
import { CheckCircle2, ShieldCheck } from "lucide-react";
import { useCart, formatPaise } from "@/components/shop/cart-provider";
import { recordOrderAction } from "@/lib/orders/record";

export default function CheckoutPage() {
  const { items, subtotalPaise, clear } = useCart();
  const [form, setForm] = useState({ name: "", phone: "", whatsapp: "", email: "", address: "", city: "", state: "", pincode: "" });
  const [submitted, setSubmitted] = useState(false);
  const [busy, setBusy] = useState(false);
  const update = (key: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setForm((current) => ({ ...current, [key]: event.target.value }));
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!items.length || form.name.trim().length < 2 || form.phone.replace(/\D/g, "").length < 10 || form.address.trim().length < 8) return; setBusy(true); await Promise.all(items.map((item) => recordOrderAction({ itemName: item.name, itemType: "PRODUCT", vendorId: item.vendorId, amount: item.pricePaise / 100 * item.quantity, amountLabel: formatPaise(item.pricePaise * item.quantity), customerName: form.name, phone: form.phone, whatsappNumber: form.whatsapp || form.phone, email: form.email, deliveryAddress: form.address, city: form.city, state: form.state, pincode: form.pincode, paymentMethod: "WHATSAPP", paymentStatus: "PENDING", source: "cart" }))); setBusy(false); setSubmitted(true); clear(); }
  if (submitted) return <section className="mx-auto flex min-h-[65vh] max-w-xl flex-col items-center justify-center gap-4 px-4 py-20 text-center"><CheckCircle2 className="size-16 text-golden" /><h1 className="font-heading text-3xl font-bold text-foreground">Order request received</h1><p className="text-muted-foreground">We have recorded your items and will contact you on WhatsApp to confirm payment and delivery.</p><Link href="/products" className="rounded-full bg-royal-purple px-6 py-3 font-semibold text-white">Continue shopping</Link></section>;
  if (!items.length) return <section className="mx-auto flex min-h-[55vh] max-w-xl flex-col items-center justify-center gap-4 px-4 text-center"><h1 className="font-heading text-3xl font-bold">Nothing to checkout</h1><Link href="/products" className="text-golden underline">Browse products</Link></section>;
  return <section className="mx-auto max-w-5xl px-4 py-12 sm:px-6"><div className="mb-8"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-golden">Secure request</p><h1 className="font-heading text-4xl font-bold text-foreground">Delivery details</h1><p className="mt-2 text-muted-foreground">Your cart is reserved while we confirm each vendor and shipping fee.</p></div><form onSubmit={submit} className="grid gap-8 lg:grid-cols-[1fr_340px]"><div className="rounded-2xl border border-border bg-card p-6"><div className="grid gap-5 sm:grid-cols-2">{([["name","Full name"],["phone","Phone number"],["whatsapp","WhatsApp number"],["email","Email address"],["city","City"],["state","State"],["pincode","Pincode"]] as const).map(([key,label]) => <label key={key} className="flex flex-col gap-2 text-sm font-medium text-foreground">{label}<input value={form[key]} onChange={update(key)} required={key === "name" || key === "phone"} type={key === "email" ? "email" : "text"} className="rounded-lg border border-border bg-background px-3 py-2.5 outline-none focus:border-golden" /></label>)}<label className="flex flex-col gap-2 text-sm font-medium text-foreground sm:col-span-2">Delivery address<textarea value={form.address} onChange={update("address")} required rows={4} className="rounded-lg border border-border bg-background px-3 py-2.5 outline-none focus:border-golden" /></label></div></div><aside className="h-fit rounded-2xl border border-border bg-card p-6 lg:sticky lg:top-28"><h2 className="font-heading text-xl font-bold">Summary</h2><div className="mt-4 flex flex-col gap-3">{items.map((item) => <div key={item.id} className="flex justify-between gap-3 text-sm"><span className="text-muted-foreground">{item.name} × {item.quantity}</span><span>{formatPaise(item.pricePaise * item.quantity)}</span></div>)}</div><div className="my-5 border-t border-border" /><div className="flex justify-between font-bold"><span>Total</span><span>{formatPaise(subtotalPaise)}</span></div><button disabled={busy} className="mt-6 w-full rounded-xl bg-royal-purple px-4 py-3 font-semibold text-white disabled:opacity-60">{busy ? "Submitting…" : "Place order request"}</button><p className="mt-4 flex gap-2 text-xs text-muted-foreground"><ShieldCheck className="size-4 shrink-0 text-golden" />No payment is captured until your order is confirmed.</p></aside></form></section>;
}
